### ISSUE TITLE
No way to get out the error from the parsing context

### ISSUE THREAD

**Issue by tamasd** [yuin/goldmark-meta#1]
Hello,

Sometimes it happens that the YAML is invalid in the metadata block. The parsing error is saved inside the `data` struct, but there is no function to get it out.

**Comment by yuin** [comment]
Errors will be rendered as an html comment.

**Comment by tamasd** [comment]
I am working on a service that parses the metadata from markdown files. I don't need HTML. I would like to avoid parsing the HTML document just to look for errors.

**Comment by yuin** [comment]
I've added a `TryGet` method.

**Comment by tamasd** [comment]
Thank you very much
