### ISSUE TITLE
Fails when first line of markdown is horizontal rule

### ISSUE THREAD

**Issue by ashtonmeuser** [yuin/goldmark-meta#5]
## Summary

Valid markdown with a first line of `---` (horizontal rule) fails to render. Markdown used:

```markdown
---

test: true
```

## Expected Behaviour

Render as follows.

```html
<hr/>

<p>test: true</p>
```

## Current Behaviour

Empty string is rendered. It seems the `BlockParser` assumes the horizontal rule is the separator for YAML metadata. Since there is no terminating separator (`---`), the entire document is read as YAML metadata.

**Comment by yuin** [comment]
This behavior is as I intended. 
To make it works as you expected, A YAML metadata block can not have blank lines(for limitation of the parsing algorithm).
